### ISSUE TITLE
Task sendo executada duas vezes

### ISSUE THREAD

**Issue by foxpv** [wpivotto/vraptor-tasks#18]
Olá pessoal,

Estou tendo um problema definindo tasks no vraptor com o vraptor-tasks. 

Eu defini minha task assim:

```java
@ApplicationScoped
@Scheduled(cron = "0 43 10 * * ?") 
public class CobrancaClienteTask implements Task {
}
```

Esse é o log no momento da execução:

```
10:43:00,043 DEBUG [DefaultJobFactory   ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
10:43:00,043 DEBUG [DefaultJobFactory   ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
10:43:00,055 DEBUG [TaskLogger          ] Executing task CobrancaClienteTask
10:43:00,055 DEBUG [TaskLogger          ] Executing task CobrancaClienteTask
2
1
6
10:43:01,205 DEBUG [TaskLogger          ] Task CobrancaClienteTask was successfully executed
2
1
6
10:43:01,205 DEBUG [TaskLogger          ] Task CobrancaClienteTask was successfully executed
```

Esses números aí eu mandei imprimir na task.

O problema é que a task está sendo executada sempre duas vezes :(
Estou usando o vraptor 3.5.3 e o vraptor-tasks 1.2.0

Porque será que isso está acontecendo?

Desde já obrigado

**Comment by jweyrich** [comment]
Me parece ser um problema no seu log. Percebendo os timestamps das mensagens, parece que o output está duplicado. Já colocastes um breakpoint para ver se ele realmente pára 2 vezes?

**Comment by foxpv** [comment]
@jweyrich
Sim! Acho que você após abrir a issue postei o log do vratpor-task e dá pra ver que ele inicializa a task duas vezes:

10:43:00,043 DEBUG [DefaultJobFactory ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
10:43:00,043 DEBUG [DefaultJobFactory ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
10:43:00,055 DEBUG [TaskLogger ] Executing task CobrancaClienteTask
10:43:00,055 DEBUG [TaskLogger ] Executing task CobrancaClienteTask

**Comment by jweyrich** [comment]
Sim, mas as linhas do output/log são idênticas (com o mesmo timestamp). Mesmo as linhas de resultado da task têm o mesmo timestamp, por isto desconfio do output/log.

**Comment by foxpv** [comment]
@jweyrich eu coloquei um breakpoint e realmente está executando duas vezes. Inclusive aqueles números (2,1,6) são syso que coloquei justamente para comprovar isso.

Parece que a task está sendo executada duas vezes em paralelo. Então creio que o problema seria algo como "duas instâncias do vraptor-tasks carregadas em paralelo". Não sei se estou falando bobagem, mas não consegui identificar :(

**Comment by wpivotto** [comment]
Também estou suspeitando da configuração do log (múltiplos appenders para o mesmo nível de log), você tem como postar ela aqui? 
De qualquer forma, qual é o output se você executar esse código:

```java

@ApplicationScoped
public TaskExecutionCounter {

	private AtomicInteger counter = new AtomicInteger();

	public int increment() {
		return counter.incrementAndGet();
	}

}

public class CobrancaClienteTask implements Task {

     private final TaskExecutionCounter counter; //receba no construtor
	 
	 void execute() {
		log.debug("Executei " + counter.increment() + " vezes");
	 }

}

```

**Comment by foxpv** [comment]
@wpivotto 
Executei com algumas modificações:
1 - Tive que tirar o final do counter pra recebe-lo no construtor da task
2 - Tive que colocar o @Component na TaskExecutionCounter pra ele ser injetado na task

```
11:22:00,007 DEBUG [DefaultJobFactory   ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
11:22:00,007 DEBUG [DefaultJobFactory   ] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
11:22:00,017 DEBUG [TaskLogger          ] Executing task CobrancaClienteTask
11:22:00,018 DEBUG [TaskLogger          ] Executing task CobrancaClienteTask
11:22:00,018 DEBUG [CobrancaClienteTask ] Executei 1 vezes
11:22:00,018 DEBUG [CobrancaClienteTask ] Executei 1 vezes
11:22:00,018 DEBUG [TaskLogger          ] Task CobrancaClienteTask was successfully executed
11:22:00,018 DEBUG [TaskLogger          ] Task CobrancaClienteTask was successfully executed
```

Pelo log, parece que é simplesmente ele sendo impresso duas vezes, porém, o fato de eu ter colocado um System.out.println pra imprimir aqueles números, e eles terem sido impressos duas vezes, não indicaria que a task está sendo executada duas vezes?

**Comment by wpivotto** [comment]
Olha, eu recomendo você a remover qualquer arquivo de configuração de log (log4j.properties) por exemplo e configurar o log via lógica, algo como:

```java
WriterAppender appender = new ConsoleAppender(new PatternLayout("%d{dd/MM/yy HH:mm:ss,SSS} %p [%F:%L] %m%n"));
BasicConfigurator.configure(appender);
Logger.getRootLogger().setLevel(Level.DEBUG);
```
e observar o output, se o resultado for o esperado o problema está na sua configuração

**Comment by foxpv** [comment]
@wpivotto 
Fiz o que você sugeriu (retirei o log4j.xml que eu tava usando). Adicionei um servlet que configura o log da mesma maneira que você postou e o problema continua.

```
19/06/15 14:04:32,204 DEBUG [QuartzSchedulerThread.java:268] batch acquisition of 1 triggers
19/06/15 14:04:49,419 DEBUG [QuartzSchedulerThread.java:268] batch acquisition of 1 triggers
19/06/15 14:05:00,008 DEBUG [AbstractBeanFactory.java:242] Returning cached instance of singleton bean 'cobrancaClienteTask'
19/06/15 14:05:00,008 DEBUG [AbstractBeanFactory.java:242] Returning cached instance of singleton bean 'cobrancaClienteTask'
19/06/15 14:05:00,008 DEBUG [DefaultJobFactory.java:35] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
19/06/15 14:05:00,008 DEBUG [DefaultJobFactory.java:35] Using br.com.caelum.vraptor.tasks.jobs.simple.DefaultJobProvider to provide br.com.opatecnologia.cobrancas.task.CobrancaClienteTask
19/06/15 14:05:00,018 DEBUG [QuartzSchedulerThread.java:268] batch acquisition of 0 triggers
19/06/15 14:05:00,018 DEBUG [QuartzSchedulerThread.java:268] batch acquisition of 0 triggers
19/06/15 14:05:00,019 DEBUG [TaskLogger.java:31] Executing task CobrancaClienteTask
19/06/15 14:05:00,020 DEBUG [JobRunShell.java:212] Calling execute on job DEFAULT.CobrancaClienteTask
19/06/15 14:05:00,019 DEBUG [TaskLogger.java:31] Executing task CobrancaClienteTask
19/06/15 14:05:00,020 DEBUG [CobrancaClienteTask.java:68] Executei 1 vezes
19/06/15 14:05:00,020 DEBUG [JobRunShell.java:212] Calling execute on job DEFAULT.CobrancaClienteTask
19/06/15 14:05:00,020 DEBUG [TaskLogger.java:41] Task CobrancaClienteTask was successfully executed
19/06/15 14:05:00,020 DEBUG [CobrancaClienteTask.java:68] Executei 1 vezes
19/06/15 14:05:00,021 DEBUG [TaskLogger.java:41] Task CobrancaClienteTask was successfully executed
```

Será que pode ter algo a ver com a versão do quartz? vou tentar atualizar ela aqui e falo.

**Comment by foxpv** [comment]
Não rolou, parece que a versão mais nova do quartz (2.2.1) não funciona.

```
Exception in thread "Thread-2" java.lang.AbstractMethodError: br.com.caelum.vraptor.tasks.TasksMonitor.schedulerStarting()V
```

**Comment by foxpv** [comment]
Indo mais a fundo, baixei o source do vraptor-tasks aqui e descobri que na inicialização do tomcat o seguinte método é executado duas vezes pra cada task:
```
public void schedule(Class<? extends Task> task, Trigger trigger, String id) {

		JobDetail detail = newJob(jobFor(task)).withIdentity(id).build();

		try {
			if(!alreadyExists(id)) {
				detail.getJobDataMap().put("task-class", task);
				detail.getJobDataMap().put("task-id", id);
				quartz.scheduleJob(detail, trigger);
			}
			else
				log.warn("Unable to schedule task {} because one already exists with this identification", task);
		} catch (SchedulerException e) {
			throw new RuntimeException(e);
		}

	}
```
E em ambas as vezes ele entra no if.

**Comment by wpivotto** [comment]
1º - Somente os logs associados ao quartz estão duplicados?
2º - Você consegue disponibilizar o projeto ou mesmo uma versão com o problema?
3º - Você tem certeza que não é algo relacionado ao seu deploy?

Te enviei um projeto exemplo por email

**Comment by foxpv** [comment]
Opa! 
Depois que o @wpivotto me pediu pra enviar uma app com o bug eu comecei a "capar" minha aplicação pra enviar e em um determinado ponto o problema parava de acontecer, então ficou claro que seria por causa de alguma configuração minha.

Aí achei isso: http://stackoverflow.com/questions/7223108/quartz-job-runs-twice-when-deployed-on-tomcat-6-ubuntu-10-04lts

Resolveu meu problema :)
