### ISSUE TITLE
Tarefas agendadas não são executadas no tempo determinado

### ISSUE THREAD

**Issue by werney** [wpivotto/vraptor-tasks#19]
Criei uma tarefa com escopo de requisição, ela executa. O problema é que é uma tarefa bem demorada, e preciso realiza-la várias vezes. Defini uma fixedRate de 5000ms e tarefa dura em média 15000ms. O ideal seria que mesmo sem encerrar a primeira ao se passar o tempo de 5000ms um outra tarefa já fosse iniciada e isso não ocorre mesmo com concurrent = true.

**Comment by wpivotto** [comment]
Estranho, as tarefas com escopo de requisição sempre deveriam executar da maneira que você descreveu. https://github.com/wpivotto/vraptor-tasks/blob/master/src/main/java/br/com/caelum/vraptor/tasks/jobs/request/RequestScopedJob.java#L14

Pode ser um bug do quartz. Você pode postar os logs?

**Comment by werney** [comment]
15:12:35,448  INFO [DefaultRequestScopedTask] Executing task in URL ...
15:12:35,811  INFO [QueryTranslatorFactoryInitiator] HHH000397: Using ASTQueryTranslatorFactory
15:12:35,904  INFO [DefaultRequestScopedTask] Task returned status code 404
15:12:57,954  INFO [DefaultRequestScopedTask] Task returned status code 200
15:12:57,956  INFO [DefaultRequestScopedTask] Executing task in URL ...
15:13:11,509  INFO [DefaultRequestScopedTask] Task returned status code 200
15:13:11,511  INFO [DefaultRequestScopedTask] Executing task in URL ...

A tarefa inicia apenas depois que a outra termina e não nos 5000ms determinados. Apaguei apenas a URL.

**Comment by wpivotto** [comment]
Ok entendi. Acabei de fazer o deploy de uma nova versão com as correções. Você pode testar e dar um feedback? obrigado

**Comment by werney** [comment]
Posso sim.

**Comment by werney** [comment]
17:47:24,277  INFO [DefaultRequestScopedTask] Executing task in URL
17:47:24,595  INFO [DefaultRequestScopedTask] Task returned status code 404
17:47:24,608 ERROR [TaskLogger          ] Task update was failed
java.lang.RuntimeException: Task failed with status code 404 at br.com.caelum.vraptor.tasks.jobs.request.DefaultRequestScopedTask.execute(DefaultRequestScopedTask.java:35) at br.com.caelum.vraptor.tasks.jobs.request.StatefulRequestScopedJob.execute(StatefulRequestScopedJob.java:28) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
17:47:44,840  INFO [DefaultRequestScopedTask] Executing task in URL
17:48:00,125  INFO [DefaultRequestScopedTask] Task returned status code 200
17:48:00,126  INFO [DefaultRequestScopedTask] Executing task in URL

Lançou essa exceção e continua executando apenas ao finalizar a primeira.

**Comment by wpivotto** [comment]
Vc anotou o método do controller? @Scheduled(fixedRate = 5000, concurrent = true)

**Comment by werney** [comment]
Não coloquei concurrent = true pq já é o default.

**Comment by werney** [comment]
Testei com concurrent = true e continua o problema.

**Comment by wpivotto** [comment]
Ok o problema é que as configurações não eram persistidas entre os schedules. Você pode tentar usar a versão 4.3.0 aqui. https://oss.sonatype.org/content/groups/public/br/com/prixma/vraptor-tasks/4.3.0/

Se funcionar para vc eu subo para o github. Obrigado

**Comment by werney** [comment]
Perfeito. Funcionando agora. Eu que agradeço.
