### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by guyihhh** [wpivotto/vraptor-tasks#20]
Tenho uma aplicação rodando quatro tasks RequestScope (tarefas diferentes e em períodos diferentes). Toda vez que inicio a aplicação recebo seguidamente três ConcurrentModificationException, no entanto as tasks são agendadas e executadas normalmente. Apenas a quarta task não gera exception.
Estou usando vraptor 3.5.3 e a versão 4.3.0 do vraptor-task.

**Comment by wpivotto** [comment]
As versões > 4.0.0 do plugin somente são compatíveis com o Vraptor 4. 
Utilize a versão 1.2.0.

**Comment by guyihhh** [comment]
Olá, testei agora com a versão 1.2.0 e a exception continua acontecendo.

**Comment by guyihhh** [comment]
Aparentemente está ocorrendo na PendingTasksInterceptor devido ao remove() no iterator `tasks.remove();` e caso eu não trate a exception sou redirecionado para a página de erro.

**Comment by wpivotto** [comment]
Ok acho que se você receber muitas requisições logo após o startup do servidor pode ocorrer de mais de um interceptor tentar fazer o schedule. Você pode tentar com a versão 1.2.1, disponível aqui https://oss.sonatype.org/content/groups/public/br/com/prixma/vraptor-tasks/1.2.1/
